name = "AI4DBiological-Systems-PublicJuliaRegistry"
uuid = "287fd9f6-e71b-44bd-9898-1d753e6c9d99"
repo = "https://github.com/AI4DBiological-Systems/PublicJuliaRegistry"
description = "Public registry of Julia packages"

[packages]
0437234d-b0b7-4786-9d16-5c3be1f5901d = { name = "ConvexClustering", path = "C/ConvexClustering" }
4c44cab3-685a-4d4f-a3f2-2eeea13c7f9a = { name = "IntervalMonoFuncs", path = "I/IntervalMonoFuncs" }
