name = "AI4DBiological-Systems-PublicJuliaRegistry"
uuid = "287fd9f6-e71b-44bd-9898-1d753e6c9d99"
repo = "https://github.com/AI4DBiological-Systems/PublicJuliaRegistry"
description = "Public registry of Julia packages"

[packages]
2c6f6ba7-1a3c-4d31-8511-d336c09a6ae6 = { name = "NMRSpecifyRegions", path = "N/NMRSpecifyRegions" }
4c44cab3-685a-4d4f-a3f2-2eeea13c7f9a = { name = "IntervalMonoFuncs", path = "I/IntervalMonoFuncs" }
